### PR TITLE
Order the browsers alphabetically in browsers.json

### PR DESCRIPTION
**Pull request by foolip**
Chrome-Edge-Firefox-Safari, also matching the wpt.fyi UI.

### CODE REVIEW

**Comment by foolip** [comment]
It's OK if this is left sitting until after March 9.

**Comment by mariestaver** [comment]
Yup, we'll get to this after 3/9 -- Thanks @foolip !

**Comment by rwaldron** [comment]
I've restarted the failed CI job

**Comment by rwaldron** [comment]
Looks like that's all it needed!

**Comment by jugglinmike** [comment]
This fell out-of-sync with `master`, where we have since inserted entries for the latest versions of Firefox (see gh-488). @foolip my fix is pretty uncontroversial, but I'm always skittish about modifying other people's commits. With your approval, I'll squash and merge this branch (note that the failure reported by TravisCI is unrelated and currently under investigation at gh-526).

**Comment by foolip** [comment]
Please squash away :)

**Pull request closed without merging**
