### PR TITLE
use unittest.mock.patch to undo ctor mocking

### PR DESCRIPTION
**Pull request by lukebjerring**
Patch is a built-in method for achieving the same thing.

### CODE REVIEW

**Comment by rwaldron** [comment]
This was really unclear to me when I was reading the docs for mock 2.0.0. It's strange that only the _patch_ method has restore-ability.

**Comment by lukebjerring** [comment]
@rwaldron I'm not sure why Travis didn't run for this PR. Will try and manually trigger a run (even if only to make it more obvious whether this caused a regression). Tests definitely passed locally.

**Comment by rwaldron** [comment]
> Tests definitely passed locally.

I had the same experience—I ran the tests locally before merging. This is really strange.

**Comment by lukebjerring** [comment]
Seeing whether it's an unrelated non-patch stub that prevents the mock getting called?
 https://github.com/w3c/wptdashboard/pull/386

**Pull request merged**
