### PR TITLE
Py2 support

### PR DESCRIPTION
**Pull request by AutomatedTester**
This is based on top of #119.

### CODE REVIEW

**Comment by jeffcarp** [comment]
Thanks for this. Looks like it needs a rebase but otherwise in general lgtm.

**Comment by gsnedders** [comment]
I'd personally prefer we kept Python 3 support, given it seems not inconceivable we'll move over to Python 3 at some point in the future.

**Comment by AutomatedTester** [comment]
@gsnedders I agree that it would have been nice but ideally we need to make sure that our runners are moved to py3, or at least py2 and py3 support, before doing this.

The current setup for wptdashboard is having both py2 and py3 setup in the same project which seems suboptimal at best.

**Comment by AutomatedTester** [comment]
rebased.

**Comment by jeffcarp** [comment]
Let's take a step back, @automatedtester what is your use case for running run/run.py? The machines it's intended for, the WPTD VMs, have no problem installing both pythons.

**Comment by jgraham** [comment]
The use case is being able to run things locally with the exact same settings as CI in order to debug problems. In this case I think that @AutomatedTester is specifically interested in the tests in `webdriver/`.

**Comment by AutomatedTester** [comment]
@jeffcarp This is because setting up this locally has proven to be near on impossible. Following good practises for python, like using a `virtualenv`, means using 2 version of python unnecessarily hard.

I am trying to fix #90 but I haven't even been able to run the tests yet. I have other setup patches locally to be able to make sure the necessary dependencies are there. Some of the dependencies  only run on Python2.7.

**Comment by bobholt** [comment]
:+1: Running locally should be both possible and easy to do in a virtualenv.

**Pull request merged**
