### PR TITLE
@mock.patch more stuff

### PR DESCRIPTION
**Pull request by lukebjerring**
Related to https://github.com/w3c/wptdashboard/pull/377, hoping to get green-ness in Travis.

### CODE REVIEW

**Comment by rwaldron** [comment]
A lot of this is changing in https://github.com/w3c/wptdashboard/pull/383

**Comment by rwaldron** [comment]
I came back to say "I think we should move forward on this, regardless of #383"... but travis is red for a new reason.

**Comment by lukebjerring** [comment]
Huzzah!~ Travis is Green. Took a while to realize it needs the module name, i.e. `run.run.patch_wpt` not `run.patch_wpt`. PTAL.

**Comment by lukebjerring** [comment]
Fixes https://github.com/w3c/wptdashboard/issues/384

**Comment by rwaldron** [comment]
This is excellent, thank you!

**Pull request merged**
