### PR TITLE
Add GetDatastoreKindName helper

### PR DESCRIPTION
**Pull request by lukebjerring**
Used in the [near future](https://github.com/mdittmer/wptdashboard/pull/3)

### CODE REVIEW

**Comment by rwaldron** [comment]
> Used in the near future

I haven't been following that PR, I see that I'm mentioned, but I must've missed. Judging by even the file/directory naming over there, the work is very much diverged from this repo and I'm concerned about the scale of merge conflict resolution that will be necessary.

**Comment by lukebjerring** [comment]
It's a single, unit-tested utility file; clashes would just be resolved with 'take theirs'. Objective here is to reduce the amount of code reviewing in the main PR-to-come.

**Comment by lukebjerring** [comment]
Done (reset main.go to the current master branch.)

**Comment by rwaldron** [comment]
@lukebjerring @mdittmer thanks! So this is still pending "[near future](https://github.com/mdittmer/wptdashboard/pull/3)"?

**Comment by lukebjerring** [comment]
I'll be sending a PR that moves the populate_dev_data to Golang, which will use this util, so now's good when you're happy.

**Comment by rwaldron** [comment]
@lukebjerring I'm not sure I follow—do you mean that this PR is ready to land now?

**Comment by lukebjerring** [comment]
Yes.

**Pull request merged**
