### PR TITLE
Remove xvfb-run

### LINKED ISSUE #444: Update: remove xvfb from script (was: xvfb should be optional)

### PR DESCRIPTION
**Pull request by mattl**
Closes #444

### CODE REVIEW

**Comment by jugglinmike** [comment]
This is what I had in mind, but we should wait to apply it until we can synchronize the change with the scripts on the machine (e.g. when the configuration management is included within this repository).

**Comment by mattl** [comment]
Sounds good. I just wanted to get this done before I forget about it.

**Comment by mattl** [comment]
@jugglinmike is this something we can merge too? I just had to remove this line on the Firefox host.

**Comment by jugglinmike** [comment]
We addressed this issue via the introduction of a Buildbot-driven infrastructure (see gh-522).

**Pull request closed without merging**
